services:
  backend:
  # ...existing code...
  services:
    backend:
      # ...existing code...
      command: >
        gunicorn
        -k uvicorn.workers.UvicornWorker
        -w 2
        -b 0.0.0.0:8000
        main:app
    # If your FastAPI app is at /app/app/main.py, use: app.main:app
# ...existing code...
    depends_on: []
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORAGE_BACKEND: ${STORAGE_BACKEND:-s3}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      HCAPTCHA_ENABLED: ${HCAPTCHA_ENABLED:-0}
      MFA_ADMIN_ENABLED: ${MFA_ADMIN_ENABLED:-1}
      NOTIFY_ON_DOWNLOAD: ${NOTIFY_ON_DOWNLOAD:-1}
      NOTIFY_OWNER_ON_TRANSFER: ${NOTIFY_OWNER_ON_TRANSFER:-1}
      JWT_SECRET: ${JWT_SECRET}
  frontend:
    environment:
      - API_BASE=${API_BASE:-http://localhost}
