---
- name: Configure Jenkins Controller
  hosts: jenkins_servers
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Java (Amazon Corretto 17)
      ansible.builtin.dnf:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Add Jenkins repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      ansible.builtin.dnf:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Git and Docker
      ansible.builtin.dnf:
        name:
          - git
          - docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

- name: Configure SecureShare App Server
  hosts: app_servers
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Git, Docker, and Docker Compose Plugin
      ansible.builtin.dnf:
        name:
          - git
          - docker
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Create application directory /opt/secureshare
      ansible.builtin.file:
        path: /opt/secureshare
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
