apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  # Base64-encoded values. Replace with your own via: 
  #   echo -n "AKIA..." | base64 -w0
  #   echo -n "<secret>" | base64 -w0
  accessKeyId: "REPLACE_BASE64_ACCESS_KEY_ID"
  secretAccessKey: "REPLACE_BASE64_SECRET_ACCESS_KEY"
